### ISSUE TITLE
Layout, styling issues

### ISSUE THREAD

**Issue by sleepylee** [ViktorArtemiev/Surveys#9]
- UI components styles are not extracted for further and easier management.
- View hierarchy optimization: we believe this [RecyclerView](https://github.com/ViktorArtemiev/Surveys/blob/430aacf42c66f1abe8ad6a281a5b589c466e8227/app/src/main/res/layout/activity_main.xml#L67) doesn't need its parent [LinearLayout](https://github.com/ViktorArtemiev/Surveys/blob/430aacf42c66f1abe8ad6a281a5b589c466e8227/app/src/main/res/layout/activity_main.xml#L57)

**Comment by ViktorArtemiev** [comment]
Hi @sleepylee 

> UI components styles are not extracted for further and easier management.

UI components styles changes can be found in the following commits:
https://github.com/ViktorArtemiev/Surveys/commit/a3844995a4743f178f3e492ccfc7e396576e9993
https://github.com/ViktorArtemiev/Surveys/commit/481ace94dbe8b8bdca58fa59a67a6bc5a5180b9e
https://github.com/ViktorArtemiev/Surveys/commit/99ff620f99e2d3adf076f27bebe7c0eaf7fa92d6

pull-request linked #17

**Comment by ViktorArtemiev** [comment]
Hi @sleepylee 

> View hierarchy optimization: we believe this RecyclerView doesn't need its parent LinearLayout

In that way, I've resolved top-bottom margin constraint issue in case we have to display more loaded items beyond the screen height (100 items for example). The problem is that [recycler_view_indicator](https://github.com/ViktorArtemiev/Surveys/blob/430aacf42c/app/src/main/res/layout/activity_main.xml#L68) ignores top-bottom margin and padding attributes within [ConstraintLayout](https://developer.android.com/reference/android/support/constraint/ConstraintLayout) view hierarchy. 

Expected without parent view group:
```
<androidx.recyclerview.widget.RecyclerView
            android:id="@+id/recycler_view_indicator"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            tools:listitem="@layout/item_indicator"
            android:layout_margin="16dp"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintTop_toBottomOf="@id/toolbar"
            app:layout_constraintBottom_toBottomOf="parent"/>
```
Video: https://drive.google.com/open?id=1HqI8nuSYD1U8OFDZIj4QiC3S7XF9DLat

![rv_without_parent](https://user-images.githubusercontent.com/5130381/62446327-1e585580-b76b-11e9-97df-15bf96c2c35a.png)

Actual with the parent view group 
(can be simply used [FrameLayout](https://developer.android.com/reference/android/widget/FrameLayout) as well):
```
    <LinearLayout
            android:layout_width="wrap_content"
            android:layout_height="0dp"
            android:padding="16dp"
            android:orientation="vertical"
            android:gravity="center"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintTop_toBottomOf="@id/toolbar"
            app:layout_constraintBottom_toBottomOf="parent">

        <androidx.recyclerview.widget.RecyclerView
                android:id="@+id/recycler_view_indicator"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center"
                tools:listitem="@layout/item_indicator"/>

    </LinearLayout>
```

Video: https://drive.google.com/open?id=1LQacCnebeDqBUq0PqnIjBnR-KeKdfytx

![rv_with_parent](https://user-images.githubusercontent.com/5130381/62446426-5bbce300-b76b-11e9-9688-11c7137c65d4.png)

Please let me know if you have any questions or we can go with this.

**Comment by sleepylee** [comment]
Hi @ViktorArtemiev, that is a very well thought on handling further scenarios, I meant the padding issue. Yet I believe a FrameLayout should be a better choice here, as it is meant to be used for such case:


>FrameLayout is designed to block out an area on the screen to display a **single item**. Generally, FrameLayout should be used to hold a single child view...
(source: [FrameLayout](https://developer.android.com/reference/android/widget/FrameLayout))

**Comment by ViktorArtemiev** [comment]
Hi @sleepylee 
The layout has been changed to [FrameLayout](https://developer.android.com/reference/android/widget/FrameLayout).
Thanks!

PR linked #20
